server:
  applicationConnectors:
    - type: http
      port: 18080
  adminConnectors:
    - type: http
      port: 18081

logging:
  level: INFO
  loggers:
    jp.gn.gonchan: DEBUG

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/matome;MVCC=TRUE;AUTO_SERVER=TRUE
